<?php

namespace ApiBundle\Repository;

/**
 * FriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $idUser
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getFriends($idUser){
        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->select('f')
            ->from('ApiBundle:Friend', 'f')
            ->where('f.idUser1 = :user')
            ->orWhere('f.idUser2  = :user')
            ->setParameter('user', $idUser);

        return $query->getQuery()->getResult();
    }
}
