<?php

namespace ApiBundle\Repository;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $idGame
     * @param $idPlayer
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getScore($idGame, $idPlayer)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $query = $qb->select('s')
            ->from('ApiBundle:Score', 's')
            ->innerJoin('s.game', 'g')
            ->where('g.id = :gameId')
            ->andWhere('s.idPlayer  = :idPlayer')
            ->setParameter('gameId', $idGame)
            ->setParameter('idPlayer', $idPlayer);

        return $query->getQuery()->getOneOrNullResult();
    }
}
